---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeaffinity-deployment
  namespace: test
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 4
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
            - containerPort: 443
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - frontend
